import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {Provider} from 'react-redux'
import {store, persistor} from './store/store'
import {Providers} from "./Provider"
import { Toaster } from "react-hot-toast";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body className={`font-sans bg-white text-black ${geistSans.variable} ${geistMono.variable}`}>
            <Providers>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </Providers>

            </body>
        </html>
    );
}
